version: 2.1

orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.4.0

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements/dev.txt
  test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Run tests
          command: python -m pytest

  deploy-to-dockerhub:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push
          command: |
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD

            docker build -t $DOCKERHUB_USER/$SERVICE_NAME:$TAG .
            docker push $DOCKERHUB_USER/$SERVICE_NAME:$TAG

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-to-dockerhub:
          requires:
            - test

on:
  push:
    branches: main