version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run: pip install -r requirements.txt --no-cache-dir
  test:
    executor: python/default
    steps:
      - checkout
      - run: pytest

  deploy-to-dockerhub:
    executor: python/default
    steps:
      - checkout
      - run: docker build -t $DOCKERHUB_USER/$SERVICE_NAME:$VERSION .
      - run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
      - run: docker push $DOCKERHUB_USER/$SERVICE_NAME:$VERSION

workflows:
  build-and-test:
    jobs:
      - build
      - test

  deploy:
    jobs:
      - deploy-to-dockerhub

on:
  push:
    branches: main