version: 2.1

orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.4.0

jobs:
  build-and-test:
    executor:
      name: python/default
      tag: '3.9'
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements/dev.txt
      - run:
          name: Run tests utils
          command: |
            export PYTHONPATH=$PYTHONPATH:$PWD/src/
            python -m pytest test_utils.py

  build-and-push-docker:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push
          command: |
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD

            docker build -t $DOCKERHUB_USER/$SERVICE_NAME:$TAG .
            docker push $DOCKERHUB_USER/$SERVICE_NAME:$TAG

workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - build-and-push-docker:
          requires:
            - build-and-test

on:
  push:
    branches: main